{
 "title": "first-light-pannel",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Current Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT reading FROM reading WHERE sensor_type = 'humidity' ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT reading FROM reading WHERE sensor_type = 'temperature' ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Light by Time ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", reading FROM reading WHERE (hardware = 'module_01_breadboard' AND sensor_type = 'light') ORDER BY \"time\" DESC LIMIT 10000 "
    }
   ]
  },
  {
   "title": "Humidity by Time ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", reading FROM reading WHERE (hardware = 'module_01_breadboard' AND sensor_type = 'humidity') ORDER BY \"time\" DESC LIMIT 10000 "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", reading FROM reading WHERE (hardware = 'module_01_breadboard' AND sensor_type = 'temperature') ORDER BY \"time\" DESC LIMIT 10000 "
    }
   ]
  },
  {
   "title": "Atmospheric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", reading FROM reading WHERE (hardware = 'module_01_breadboard' AND sensor_type = 'pressure') ORDER BY \"time\" DESC LIMIT 10000 "
    }
   ]
  },
  {
   "title": "Gas: Volatile Organic Compounds (VOC) like ethanol and carbon monoxide",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kohm" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", reading FROM reading WHERE (hardware = 'module_01_breadboard' AND sensor_type = 'gas') ORDER BY \"time\" DESC LIMIT 10000 "
    }
   ]
  }
 ]
}